# Cloudflare Pages
# https://developers.cloudflare.com/pages/functions/wrangler-configuration/

name = "space-radio"
pages_build_output_dir = "./dist"
compatibility_date = "2026-01-18"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[observability]
enabled = true


# KV Namespace Bindings
[[kv_namespaces]]
binding = "LIKES"
id = "bfca45c77224430683574746d8a7069f"
