# Cloudflare Pages
# https://developers.cloudflare.com/pages/functions/wrangler-configuration/

name = "space-radio"
main = "./dist/_worker.js/index.js"
compatibility_date = "2026-01-18"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[vars]
PUBLIC_REMARK_URL="https://remark42.spacerad.io"
PUBLIC_REMARK_SITE_ID="space-radio"

[[kv_namespaces]]
binding = "LIKES"
id = "bfca45c77224430683574746d8a7069f"
